# Generated by Django 5.2.7 on 2025-10-13 14:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voter',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'election')},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='party',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='votes',
        ),
        migrations.AddField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
